# Generated by Django 4.1.4 on 2023-01-21 15:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('modifiedAt', models.DateTimeField(auto_created=True)),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('active', models.BooleanField(default=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('modifiedAt', models.DateTimeField(auto_created=True)),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('active', models.BooleanField(default=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('modifiedAt', models.DateTimeField(auto_created=True)),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('active', models.BooleanField(default=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.country')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifiedAt', models.DateTimeField(auto_created=True)),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='')),
                ('startTime', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.video')),
            ],
        ),
    ]
