# Generated by Django 4.1.4 on 2022-12-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='countryName',
            new_name='name',
        ),
    ]
