# Generated by Django 4.1.4 on 2023-01-21 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoaction',
            name='videoId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.video'),
        ),
    ]
