# Generated by Django 4.1.4 on 2023-01-21 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_videoaction_videoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoaction',
            name='videoId',
        ),
        migrations.AlterField(
            model_name='videoaction',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.video'),
        ),
    ]
