# Generated by Django 4.1.4 on 2022-12-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_countryname_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='image',
        ),
        migrations.AlterField(
            model_name='country',
            name='modifiedAt',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
