# Generated by Django 4.1.4 on 2023-01-21 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_videoaction_videoid_alter_videoaction_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoaction',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
