# Generated by Django 4.1.4 on 2022-12-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_country_image_alter_country_modifiedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
