# Generated by Django 4.1.4 on 2022-12-20 17:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_country_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('modifiedAt', models.DateTimeField(auto_created=True)),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('active', models.BooleanField(default=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VideoAction',
            fields=[
                ('modifiedAt', models.DateTimeField(auto_created=True)),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('startTime', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('active', models.BooleanField(default=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('modifiedAt', models.DateTimeField(auto_created=True)),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('active', models.BooleanField(default=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.country'),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
