# Generated by Django 4.1.4 on 2023-01-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_videoaction_videoid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoAction',
        ),
    ]
