# Generated by Django 4.1.4 on 2023-01-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category_alter_country_active_videoaction_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category'),
        ),
    ]
